package main;

import (
	"fmt"
	"github.com/gin-gonic/gin"
	// "github.com/swaggo/http-swagger"
	"github.com/lailacha/go-MarketAPI_esgi/server/broadcaster"
	"github.com/lailacha/go-MarketAPI_esgi/server/payement"
	"github.com/lailacha/go-MarketAPI_esgi/server/product"
	adapter "github.com/lailacha/go-MarketAPI_esgi/server/adapter"
	"gorm.io/gorm"
	"log"
	"gorm.io/driver/mysql"
	// "github.com/gin-gonic/gin"
	// "github.com/swaggo/files"
	// "github.com/swaggo/gin-swagger"

	// "/docs" // docs is generated by Swag CLI, you have to import it.
)

func main() {

	router := gin.Default()


	//create the connection to the db

	dbURL := "user:password@tcp(127.0.0.1:3306)/go-exam?charset=utf8mb4&parseTime=True&loc=Local"


	db, err := gorm.Open(mysql.Open(dbURL), &gorm.Config{})
	if err != nil {
		log.Fatal(err.Error())
	}


	// run a migration to create the tables
	db.AutoMigrate(&payement.Payement{})
	db.AutoMigrate(&product.Product{})

	// create the repository and the services
	//productRepository := product.NewProductRepository(db)
	//productService := product.NewService(productRepository)


	payementRepository := payement.NewPayementRepository(db)
	payementService := payement.NewService(payementRepository)


	productRepository := product.NewProductRepository(db)
	productService := product.NewService(productRepository)

	// http.Handle("/docs/", http.StripPrefix("/docs/", httpSwagger.Handler(httpSwagger.URL("/docs/swagger.yaml"))))


	// get the broadcaster
	b := broadcast.NewBroadcaster(20)
	
	ginAdapter := adapter.NewGinAdapter(b, productService, payementService)

	router.GET("/stream", ginAdapter.Stream)
	
	router.POST("/createPayement", ginAdapter.CreatePayement)
	router.GET("/getPayement/:id", ginAdapter.GetPayement)
	router.PUT("/updatePayement/:id", ginAdapter.UpdatePayement)
	router.DELETE("/deletePayement/:id", ginAdapter.DeletePayement)
	router.GET("/getPayements", ginAdapter.GetPayements)

	router.POST("/createProduct", ginAdapter.CreateProduct)
	router.PUT("/updateProduct/:id", ginAdapter.UpdateProduct)
	router.DELETE("/deleteProduct/:id", ginAdapter.DeleteProduct)
	router.GET("/getProduct/:id", ginAdapter.GetProduct)
	router.GET("/getProducts", ginAdapter.GetProducts)

	router.Run(fmt.Sprintf(":%v", 8084))

	
	// programmatically set swagger info
	// docs.SwaggerInfo.Title = "Swagger Example API"
	// docs.SwaggerInfo.Description = "This is a sample server Petstore server."
	// docs.SwaggerInfo.Version = "1.0"
	// docs.SwaggerInfo.Host = "petstore.swagger.io"
	// docs.SwaggerInfo.BasePath = "/v2"
	// docs.SwaggerInfo.Schemes = []string{"http", "https"}

	// r := gin.New()

	// // use ginSwagger middleware to serve the API docs
	// r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// r.Run()

	// run the broadcaster

}